name: Build Conda packages
description: Build the Conda packages
runs:
  using: composite
  steps:
    - uses: conda-incubator/setup-miniconda@v3
      # Adapted from https://github.com/conda-incubator/setup-miniconda/blob/v3.2.0/README.md#example-14-remove-defaults-channel.
      with:
        channels: conda-forge
        conda-build-version: "25.9.0"
        conda-remove-defaults: "true"
        miniforge-version: "25.3.1-0"

    - run: conda build --output-folder dist .
      # See https://github.com/conda-incubator/setup-miniconda/blame/059455a698430d8b68fa317268fa2e3da3492a98/README.md#L609-L610.
      shell: bash -el {0}

    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: jdk4py-${{ runner.os }}-${{ runner.arch }}-conda-packages
        path: dist/*/jdk4py-*.conda
