name: Build Conda packages
description: Build the Conda packages
runs:
  using: composite
  steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        conda-build-version: "25.9.0"
        conda-remove-defaults: true
        miniforge-version: "25.3.1-0"

    - if: ${{ runner.os != 'Windows' }}
      run: cat ~/.condarc
      shell: bash -l {0}

    # See https://github.com/conda/conda/issues/12563#issuecomment-1494264704.
    - if: ${{ runner.os == 'Windows' }}
      run: echo "LIBARCHIVE=C:\\Miniconda\\Library\\bin\\archive.dll" >> "$GITHUB_ENV"
      shell: bash -l {0}

    - run: conda build --no-anaconda-upload --output-folder dist .
      # See https://github.com/conda-incubator/setup-miniconda/blame/059455a698430d8b68fa317268fa2e3da3492a98/README.md#L609-L610.
      shell: bash -l {0}

    - if: ${{ runner.os != 'Windows' }}
      run: ls dist
      shell: bash -l {0}
