# Remove this action and inline the first step once https://github.com/astral-sh/uv/issues/14827 is closed.
name: Build Python wheel
description: Build platform-specific Python wheel
runs:
  using: composite
  steps:
    - run: uv build --wheel
      shell: bash

    - run: uv run python -m wheel tags --platform-tag ${{ env.JDK4PY_PLATFORM_TAG }} --remove dist/*-py3-none-any.whl
      env:
        # Tag values taken from https://pypi.org/project/numpy/2.1.0/#files.
        JDK4PY_PLATFORM_TAG: ${{ (runner.os == 'Linux' && runner.arch == 'ARM64' && 'manylinux_2_17_aarch64') || (runner.os == 'Linux' && runner.arch == 'X64' && 'manylinux_2_17_x86_64') || (runner.os == 'macOS' && runner.arch == 'ARM64' && 'macosx_11_0_arm64') || (runner.os == 'macOS' && runner.arch == 'X64' && 'macosx_10_9_x86_64') || (runner.os == 'Windows' && runner.arch == 'X64' && 'win_amd64') || '' }}
      shell: bash
