name: Build Java runtime
description: Build the Java runtime and upload it as an artifact.
runs:
  using: composite
  steps:
    - id: get-java-version
      run: uv run python -c 'from jdk4py import JAVA_VERSION; print(f"""version={".".join(str(number) for number in JAVA_VERSION)}""")' >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ steps.get-java-version.outputs.version }}

    - run: uv run python build_java_runtime.py
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: ${{ matrix.runner }}-java-runtime
        path: src/jdk4py/java-runtime/
