name: Build Java runtime
description: Build the Java runtime after installing the required dependencies.
inputs:
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v2
      with:
        cache-dependency-glob: "uv.lock"
        enable-cache: true
        version: "0.4.7"

    - run: uv python install ${{ inputs.python-version }}
      shell: bash

    - run: uv sync --locked
      shell: bash

    - id: get-java-version
      run: uv run python -c 'from jdk4py import JAVA_VERSION; print(f"""version={".".join(str(number) for number in JAVA_VERSION)}""")' >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ steps.get-java-version.outputs.version }}

    - run: uv run python build_java_runtime.py
      shell: bash
