name: Build Java runtime
description: Build the Java runtime after installing the required dependencies.
inputs:
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    - if: ${{ runner.os != 'windows-2022' }}
      run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh
      shell: bash

    - if: ${{ runner.os == 'windows-2022' }}
      run: irm https://astral.sh/uv/0.4.0/install.ps1 | iex
      shell: powershell

    - run: uv python install ${{ inputs.python-version }}
      shell: bash

    - run: uv sync --locked
      shell: bash

    - id: get-java-version
      run: uv run python -c 'from jdk4py import JAVA_VERSION; print(f"""version={".".join(str(number) for number in JAVA_VERSION)}""")' >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ steps.get-java-version.outputs.version }}

    - run: uv run python build_java_runtime.py
      shell: bash
