name: Build Java runtime
description: Build the Java runtime.
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v6
      with:
        version-file: pyproject.toml

    - id: get-java-version
      run: uv run python -c 'from jdk4py import JAVA_VERSION; print(f"""version={".".join(str(number) for number in JAVA_VERSION)}""")' >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ steps.get-java-version.outputs.version }}

    - run: uv run python build_java_runtime.py
      shell: bash
