name: Build Java runtime
description: Build the Java runtime after installing the required dependencies.
inputs:
  os:
    description: The OS of the runner.
    required: true
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    - if: ${{ inputs.os != 'windows-2022' }}
      run: curl -LsSf https://astral.sh/uv/0.4.0/install.sh | sh
      shell: bash

    - if: ${{ inputs.os == 'windows-2022' }}
      run: irm https://astral.sh/uv/0.4.0/install.ps1 | iex
      shell: powershell

    - run: uv python install ${{ inputs.python-version }}
      shell: bash

    - run: uv sync --locked
      shell: bash

    - run: uv run python scripts/set_environment.py
      shell: bash

    - id: get-java-version
      run: echo "java-version=$(cat src/jdk4py/java_version.txt)" >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ steps.get-java-version.outputs.java-version }}

    - run: uv run python scripts/build_java_runtime.py
      shell: bash
