name: Build Java runtime
description: Build the Java runtime after installing the required dependencies.
inputs:
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}
        version: "0.5.16" # Keep synced with same field in `deployment.yaml`.

    - id: get-java-version
      run: uv run python -c 'from jdk4py import JAVA_VERSION; print(f"""version={".".join(str(number) for number in JAVA_VERSION)}""")' >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ steps.get-java-version.outputs.version }}

    - run: uv run python build_java_runtime.py
      shell: bash
