name: Build JDK
description: Install the dependencies and build the JDK
inputs:
  os:
    description: The OS of the runner.
    required: true
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    # Remove once pipx is preinstalled on this OS.
    - if: ${{ inputs.os == 'macos-latest-xlarge' }}
      name: Install pipx
      run: brew install pipx && echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - run: pipx install poetry==1.7.0
      shell: bash

    - run: poetry --version
      shell: bash

    - id: setup_python
      uses: actions/setup-python@v4
      with:
        # Not using cache on Apple Silicon to avoid clash with Intel macOS runner (they both have `RUNNER_OS` set to `macOS`).
        # See https://github.com/actions/setup-python/blob/b64ffcaf5b410884ad320a9cfac8866006a109aa/src/cache-distributions/poetry-cache.ts#L50.
        cache: ${{ inputs.os == 'macos-latest-xlarge' && '' || 'poetry' }}
        python-version: ${{ inputs.python-version }}

    - run: poetry install
      shell: bash

    - run: poetry run python scripts/set_environment.py
      shell: bash

    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ env.JDK4PY_JAVA_VERSION }}

    - run: poetry run python scripts/build_jdk.py
      shell: bash
