name: Build JDK
description: Install the dependencies and build the JDK
inputs:
  architecture:
    description: The target architecture.
    required: true
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    # - id: setup_python
    #   uses: actions/setup-python@v4
    #   with:
    #     architecture: ${{ inputs.architecture }}
    #     python-version: ${{ inputs.python-version }}

    - run: python --version
      shell: bash

    - name: Check Python version
      run: python -c 'import sys; expected_version = tuple([int(number) for number in sys.argv[-1].split(".")]); assert sys.version_info[:2] == expected_version[:2], f"Expected Python version {expected_version} but got {sys.version_info}."' ${{ inputs.python-version }}
      shell: bash

    - run: pip install poetry==1.7.0
      shell: bash

    - run: poetry install
      shell: bash

    - run: poetry run python scripts/set_environment.py
      shell: bash

    - uses: actions/setup-java@v3
      with:
        architecture: ${{ inputs.architecture }}
        distribution: temurin
        java-version: ${{ env.JDK4PY_JAVA_VERSION }}

    - run: poetry run python scripts/build_jdk.py
      shell: bash
