name: Build JDK
description: Install the dependencies and build the JDK
inputs:
  os:
    description: The OS of the runner.
    required: true
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: composite
  steps:
    # Remove once pipx is preinstalled on this OS.
    - if: ${{ inputs.os == 'macos-14' }}
      name: Install pipx
      run: brew install pipx && echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - run: pipx install poetry==1.7.1
      shell: bash

    - id: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - run: poetry check --lock
      shell: bash

    - run: poetry install
      shell: bash

    - run: poetry run python scripts/set_environment.py
      shell: bash

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JDK4PY_JAVA_VERSION }}

    - run: poetry run python scripts/build_jdk.py
      shell: bash
