name: Build JDK
description: Install the dependencies and build the JDK
inputs:
  architecture:
    description: The architecture targeted by the JDK to set up.
    required: true
  python-version:
    description: The version of Python to set up.
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        # No need to set the architecture for Python because jdk4py is platform independent Python-wise.
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: pip install poetry

    - name: Install Python dependencies
      shell: bash
      run: poetry install

    - name: Set environment variables
      shell: bash
      run: poetry run python scripts/set_environment.py
      env:
        JDK4PY_ARCHITECTURE: ${{ inputs.architecture }}

    - uses: actions/setup-java@v2
      with:
        architecture: ${{ inputs.architecture }}
        distribution: temurin
        java-version: ${{ env.JDK4PY_JAVA_VERSION }}

    - name: Build JDK
      shell: bash
      run: poetry run python scripts/build_jdk.py
      env:
        JDK4PY_ARCHITECTURE: ${{ inputs.architecture }}
