name: Create Python wheel
description: Create a Python wheel
inputs:
  build-number:
    description: The build number of the wheel.
    required: true
runs:
  using: "composite"
  steps:
    - name: Build Python wheel
      run: poetry run python setup.py bdist_wheel --build-number ${{ inputs.build-number }}
      shell: bash
