name: Create Python wheel
description: Create a Python wheel
runs:
  using: "composite"
  steps:
    - name: Build Python wheel
      shell: bash
      run: poetry run python setup.py bdist_wheel --build-number $JDK4PY_BUILD_NUMBER
