{% set version = load_file_data("src/jdk4py/version.json") %}

package:
  name: jdk4py
  version: {{ version}}

source:
  path: ../

build:
  # Binaries are broken on macOS without it.
  binary_relocation: False
  include_recipe: False

requirements:
  build:
    # Keep in sync with version in `pyproject.toml`.
    - hatchling ==1.25.0
    - python {{ python }}
    - pip ==24.2
  run:
    - python {{ python }}

test:
  source_files:
    - tests/**
  requires:
    # Keep in sync with version in `pyproject.toml`.
    - pytest ==8.3.2
  commands:
    - pytest

about:
  home: https://github.com/activeviam/jdk4py
  license: GNU General Public License v2.0
  license_file: LICENSE
  summary: Packaged JDK for Python.
  dev_url: https://github.com/activeviam/jdk4py

extra:
  recipe-maintainers:
    - ActiveViam
