{% set pyproject = load_file_data("pyproject.toml") %}
{% set dev_dependencies = pyproject["dependency-groups"]["dev"] %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ pyproject["project"]["version"] }}

source:
  path: ../

build:
  include_recipe: False
  script: "uv pip install ."

requirements:
  build:
    - "uv {{ pyproject["tool"]["uv"]["required-version"] }}"

test:
  source_files:
    - tests/
  requires:
    {% for dependency in dev_dependencies if dependency.startswith("pytest ==") %}
      - "{{ dependency }}"
    {% endfor %}
  commands:
    - pytest

about:
  dev_url: {{ pyproject["project"]["urls"]["Repository"] }}
  license: GNU General Public License v2.0
  license_file: LICENSE
  summary: {{ pyproject["project"]["description"] }}

extra:
  recipe-maintainers:
  {% for author in pyproject["project"]["authors"] %}
    - {{ author["name"] }}
  {% endfor %}
