{% set pyproject = load_file_data("pyproject.toml") %}
{% set dev_dependencies = pyproject["tool"]["uv"]["dev-dependencies"] %}
{% set version = load_file_data("src/jdk4py/version.json") %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ version }}

source:
  path: ../

build:
  # Binaries are broken on macOS without it.
  binary_relocation: False
  include_recipe: False
  missing_dso_whitelist:
    - "*.dylib"

requirements:
  build:
    - python {{ python }}
    - pip ==24.2
  {% for dependency in dev_dependencies if dependency.startswith("hatchling ") %}
    - {{ dependency }}
  {% endfor %}
  run:
    - python {{ python }} # See https://github.com/activeviam/jdk4py/issues/34.

test:
  source_files:
    - tests/
  requires:
    {% for dependency in dev_dependencies if dependency.startswith("pytest ") %}
      - {{ dependency }}
    {% endfor %}
  commands:
    - pytest

about:
  dev_url: {{ pyproject["project"]["urls"]["Repository"] }}
  license: GNU General Public License v2.0
  license_file: LICENSE
  summary: {{ pyproject["project"]["description"] }}

extra:
  recipe-maintainers:
  {% for author in pyproject["project"]["authors"] %}
    - {{ author["name"] }}
  {% endfor %}
