{% set pyproject = load_file_data("pyproject.toml") %}
{% set dev_dependencies = pyproject["dependency-groups"]["dev"] %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ pyproject["project"]["version"] }}

source:
  path: ../

build:
  # Binaries are broken on macOS without it.
  binary_relocation: False
  include_recipe: False

requirements:
  build:
    - python {{ python }}
    - pip ==25.2
  {% for dependency in dev_dependencies if dependency.startswith("hatchling ") %}
    - {{ dependency }}
  {% endfor %}
  run:
    - python {{ python }}

test:
  source_files:
    - tests/
  requires:
    {% for dependency in dev_dependencies if dependency.startswith("pytest ") %}
      - {{ dependency }}
    {% endfor %}
  commands:
    - pytest

about:
  dev_url: {{ pyproject["project"]["urls"]["Repository"] }}
  license: GNU General Public License v2.0
  license_file: LICENSE
  summary: {{ pyproject["project"]["description"] }}

extra:
  recipe-maintainers:
  {% for author in pyproject["project"]["authors"] %}
    - {{ author["name"] }}
  {% endfor %}
