name: Platform-specific build
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  build-conda-packages:
    name: Build Conda packages on ${{ inputs.runner }}
    needs: build-java-runtime
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-java-runtime
      - uses: ./.github/actions/build-conda-packages

  build-java-runtime:
    name: Build Java runtime on ${{ inputs.runner }}
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/build-java-runtime

      # See https://github.com/actions/upload-artifact/blob/v4.6.2/README.md#permission-loss.
      - run: tar -cf artifact.tar src/jdk4py/java-runtime/
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: java-runtime-${{ runner.os }}-${{ runner.arch }}
          path: artifact.tar

      - run: rm artifact.tar
        shell: bash

  # build-python-wheel:
  #   name: Build Python wheel on ${{ inputs.runner }}
  #   needs: build-java-runtime
  #   runs-on: ${{ inputs.runner }}
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: ./.github/actions/install-java-runtime
  #     - uses: astral-sh/setup-uv@v6
  #       with:
  #         version-file: pyproject.toml
  #     - uses: ./.github/actions/build-python-wheel
